
from Gui import Colors
from Gui import Fonts


WELCOME_LOGO_COLOR       = Colors.COLOR_BS_LIGHT
WELCOME_LOGO_FONT        = Fonts.FONT_GEOLOGICA_BLACK
WELCOME_LOGO_FONT_WEIGHT = Fonts.Font.Black
WELCOME_LOGO_FONT_SIZE   = 48

WELCOME_OPEN_PROJECT_COLOR       = Colors.COLOR_BS_LIGHT
WELCOME_OPEN_PROJECT_FONT        = Fonts.FONT_GEOLOGICA_BLACK
WELCOME_OPEN_PROJECT_FONT_WEIGHT = Fonts.Font.Black
WELCOME_OPEN_PROJECT_FONT_SIZE   = 18
